### ISSUE TITLE
D9 verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1182]
- [x] In my verification role, if I try to edit someone else's record, I get an error message "Attempt to access a record you did not create"
- [x] Can we make the "Query" box so that it doesn't need a scroll bar, unless you are adding a very long comment?:
![image](https://user-images.githubusercontent.com/16039111/143687797-7d7f4904-7746-466c-ac36-9ea12d85f4a2.png)

**Comment by johnvanbreda** [comment]
I've fixed the scrollbars - @BirenRathod, I fixed this by removing the following CSS from node.7614.css:
```css
.ui-tabs-panel {
	overflow-y: auto;
    display: block;
    max-height: 300px;
}
```

I also removed the following which caused the grid height to be too small, not filling the page:
```css
.es-data-grid tbody {
	max-height: 520px !important;
	display: block;
}
.idc-output-leafletMap {
	max-height: 320px;
}
```

Do you know where these CSS snippets came from? I don't think they were on iRecord.

Also, the verification role doesn't have access to edit existing records. Editing an existing record currently needs the indicia data admin permission, but the verification role doesn't have this permission. Do you know if the "Permission required for editing other people's data" setting on the form edit tabs has changed, or is it the verification role that has lost the "indicia data admin" permission? I can't see the old iRecord to check at the moment.
