### ISSUE TITLE
iRecord drupal 8 website

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#976]
Hello All

I have updated iRecord site to Drupal 8 now. Below are my issue which still needs to resolve and add comments i you have any suggestions.

**Biren**
- [x] Install Indicia API v1
- [x] Update Indicia API v1 - there is an a new hotfix applied to it
- [x] Enable CORS support - see below comment

**John**
1. The schemes logo is not appearing at present.
2. To check particular node related CSS & JS work fine or not.
3. PHP code is not working same way as in Drupal 7, that is why, I haven't added the map & photos. 
4. In the current iRecord (Drupal 7) site, there is one indicia page node 635 (www.brc.ac.uk/irecord/services/data) is not working on new site, so I haven't migrated yet.

**Karolis**
- [x] Test Indicia API v1 module works with iRecord App

**David**
5. I haven't added all survey summaries in "Survey summaries" menu link only the latest one. Those reports need to update as it is not ES. Do we need all reports in it?

6. All links in help submenu are now index alphabetically except 'iRecord user guide'. 

The URL of the website is -> https://test-brc-irecord.pantheonsite.io/

**Comment by kazlauskis** [comment]
@BirenRathod I am not aware of the **node 635**. I have tried to open it now but it has timed out. Is this is something to do with Indicia data exchange?

**Comment by BirenRathod** [comment]
@kazlauskis I have no idea about it. On the live site URL is taking so long due to huge chunk of data and end up in time out. 

@johnvanbreda -> The service/data link using a taxon group 130 & 150 and it uses the this 'Data Service. Occurrences Download using standard filters' report from occurrences folder.

**Comment by johnvanbreda** [comment]
@kazlauskis here's the initial commit of the data services form - https://github.com/Indicia-Team/client_helpers/commit/48040e74761cb9a255ff9d3a55d48dc9954dd980#diff-fe22d839dd42c404ea1e8b388c9bbcb877906701d2d0c397825593ba8ab3ec31. I'm not sure what it was for, so unless you know otherwise I suggest we delete lt.

@BirenRathod 3. I agree we should not use the PHP filter anymore. Instead we should use a custom module which declares some blocks. Then we should use layout builder to create the page layouts.
1. The schemes logo will need some custom work in the theme's template (maybe the branding template)?

**Comment by BirenRathod** [comment]
@johnvanbreda Are you going to do custom module & branding template work?

**Comment by kazlauskis** [comment]
I can't remember what the node 635 was for and searching through various places couldn't find any leads. It was shortly after I have started the work at CEH so Jim Bacon might now more about this. I suggest deleting it too.

**Comment by kazlauskis** [comment]
@BirenRathod I have added a task for Indicia API in the description.

**Comment by johnvanbreda** [comment]
@BirenRathod I'd need @DavidRoy to confirm that I should be working on this rather than other priorities.

**Comment by BirenRathod** [comment]
@kazlauskis Indicia API has already installed & enabled it.

**Comment by kazlauskis** [comment]
> @kazlauskis Indicia API has already installed & enabled it.

This is `v2`, the `v1` is in different branch. Ideally we should have both of them but I am not sure how well they will play with each other. The `v1` is the important one now.

**Comment by BirenRathod** [comment]
@kazlauskis In that case, shall I leave V2 version or Do I have to remove it first?

**Comment by kazlauskis** [comment]
Remove it.

**Comment by BirenRathod** [comment]
@kazlauskis I removed the API V2 & installed & enabled API V1.

**Comment by kazlauskis** [comment]
I have tested the iRecord App with the test site and it mostly worked fine. There are a few small tweaks remaining which I have added as tasks to the description above. One of those is adding CORS support by modifying the `sites/default/services.yml`

```YAML
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['authorization', 'x-api-key', 'content-type']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['GET', 'POST', 'PUT', 'OPTIONS']
    # Configure requests allowed from specific origins.
    allowedOrigins: ['*']
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: false
    # Sets the Access-Control-Max-Age header.
    maxAge: false
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: false
```
